# -*- mode: ruby -*-
# vi: set ft=ruby :
# xrubocop:disable Metrics/LineLength
# rubocop:disable Metrics/BlockLength

#
# NOTE: production simulation (sim) held back to node v4.4.5 for omnios
#       omnibus nad packages use node 6.x
#
node_base_url = 'https://nodejs.org/download/release'
nad_url = 'http://updates.circonus.net/node-agent/packages/nad-omnibus-2.0.2-1.el7.x86_64.rpm'

Vagrant.configure(2) do |config|
    config.vm.define 'dev', primary: true, autostart: true do |bx|
        node_ver = 'v6.10.2'
        bx.vm.box = 'maier/centos-7.2.1511-x86_64'
        bx.vm.hostname = 'cosi-cli-dev'
        bx.vm.synced_folder '.', '/vagrant', disabled: true
        bx.vm.synced_folder '../..', '/home/vagrant/cosi'
        bx.vm.provider 'virtualbox' do |vb|
            vb.cpus = 2
            vb.memory = 2048
        end
        bx.vm.provision 'node', type: 'shell', inline: <<-SHELL
            [[ -d /opt/node ]] || mkdir -p /opt/node
            NODE_TGZ="node-#{node_ver}-linux-x64.tar.gz"
            NODE_URL="#{node_base_url}/#{node_ver}/${NODE_TGZ}"
            echo "Installing NodeJS - $NODE_URL"
            [[ -f /opt/node/$NODE_TGZ ]] || curl -s "${NODE_URL}" -o /opt/node/${NODE_TGZ}
            [[ -x /opt/node/bin/node ]] || {
                echo "Unpacking $NODE_TGZ"
                tar -zx -C /opt/node --strip-components=1 -f "/opt/node/${NODE_TGZ}"
                echo 'export PATH=$PATH:/opt/node/bin' > /etc/profile.d/nodejs.sh
            }
            date > /home/vagrant/provision_node.timestamp
        SHELL
    end

    config.vm.define 'sim', primary: false, autostart: false do |bx|
        node_ver = 'v4.4.5'
        bx.vm.box = 'maier/centos-7.2.1511-x86_64'
        bx.vm.hostname = 'cosi-cli-sim'
        bx.vm.synced_folder '.', '/vagrant', disabled: true
        bx.vm.synced_folder '../..', '/home/vagrant/cosi'
        bx.vm.provider 'virtualbox' do |vb|
            vb.cpus = 2
            vb.memory = 2048
        end
        bx.vm.provision 'node', type: 'shell', inline: <<-SHELL
            [[ -d /opt/node ]] || mkdir -p /opt/node
            NODE_TGZ="node-#{node_ver}-linux-x64.tar.gz"
            NODE_URL="#{node_base_url}/#{node_ver}/${NODE_TGZ}"
            echo "Installing NodeJS - $NODE_URL"
            [[ -f /opt/node/$NODE_TGZ ]] || curl -s "${NODE_URL}" -o /opt/node/${NODE_TGZ}
            [[ -x /opt/node/bin/node ]] || {
                echo "Unpacking $NODE_TGZ"
                tar -zx -C /opt/node --strip-components=1 -f "/opt/node/${NODE_TGZ}"
            }
            date > /home/vagrant/provision_node.timestamp
        SHELL
    end

    #
    # common provision
    #
    config.vm.provision 'common', type: 'shell', inline: <<-SHELL
        echo "Updating cache"
        yum -q -e 0 makecache fast
        echo "Updating packages"
        yum -q update -y
        echo "Installing git"
        yum -q install -y git
        [[ -x /opt/circonus/sbin/nad ]] || {
            echo "Installing NAD"
            rpm -Uvh --nodeps "#{nad_url}"
        }
        date > /home/vagrant/provision_common.timestamp
    SHELL
end
